import * as basicValidatorsRaw from './basic.js';

import { markSafeIterative } from './utils/parseObject/mark-safe.js';

/******************************************************************************
                                  Export
******************************************************************************/

export const {
  // Nullables
  isUndef,
  isNull,
  isNullish,
  // Boolean
  isBoolean,
  isOptionalBoolean,
  isNullableBoolean,
  isNullishBoolean,
  isBooleanArray,
  isOptionalBooleanArray,
  isNullableBooleanArray,
  isNullishBooleanArray,
  // Valid boolean
  isValidBoolean,
  isOptionalValidBoolean,
  isNullableValidBoolean,
  isNullishValidBoolean,
  isValidBooleanArray,
  isOptionalValidBooleanArray,
  isNullableValidBooleanArray,
  isNullishValidBooleanArray,
  // Number
  isNumber,
  isOptionalNumber,
  isNullableNumber,
  isNullishNumber,
  isNumberArray,
  isOptionalNumberArray,
  isNullableNumberArray,
  isNullishNumberArray,
  // Positive Number
  isPositiveNumber,
  isOptionalPositiveNumber,
  isNullablePositiveNumber,
  isNullishPositiveNumber,
  isPositiveNumberArray,
  isOptionalPositiveNumberArray,
  isNullablePositiveNumberArray,
  isNullishPositiveNumberArray,
  // Negative Number
  isNegativeNumber,
  isOptionalNegativeNumber,
  isNullableNegativeNumber,
  isNullishNegativeNumber,
  isNegativeNumberArray,
  isOptionalNegativeNumberArray,
  isNullableNegativeNumberArray,
  isNullishNegativeNumberArray,
  // Unsigned Number
  isUnsignedNumber,
  isOptionalUnsignedNumber,
  isNullableUnsignedNumber,
  isNullishUnsignedNumber,
  isUnsignedNumberArray,
  isOptionalUnsignedNumberArray,
  isNullableUnsignedNumberArray,
  isNullishUnsignedNumberArray,
  // Integer
  isInteger,
  isOptionalInteger,
  isNullableInteger,
  isNullishInteger,
  isIntegerArray,
  isOptionalIntegerArray,
  isNullableIntegerArray,
  isNullishIntegerArray,
  // Positive Integer
  isPositiveInteger,
  isOptionalPositiveInteger,
  isNullablePositiveInteger,
  isNullishPositiveInteger,
  isPositiveIntegerArray,
  isOptionalPositiveIntegerArray,
  isNullablePositiveIntegerArray,
  isNullishPositiveIntegerArray,
  // Negative Integer
  isNegativeInteger,
  isOptionalNegativeInteger,
  isNullableNegativeInteger,
  isNullishNegativeInteger,
  isNegativeIntegerArray,
  isOptionalNegativeIntegerArray,
  isNullableNegativeIntegerArray,
  isNullishNegativeIntegerArray,
  // Unsigned Integer
  isUnsignedInteger,
  isOptionalUnsignedInteger,
  isNullableUnsignedInteger,
  isNullishUnsignedInteger,
  isUnsignedIntegerArray,
  isOptionalUnsignedIntegerArray,
  isNullableUnsignedIntegerArray,
  isNullishUnsignedIntegerArray,
  // BigInt
  isBigInt,
  isOptionalBigInt,
  isNullableBigInt,
  isNullishBigInt,
  isBigIntArray,
  isOptionalBigIntArray,
  isNullableBigIntArray,
  isNullishBigIntArr,
  // Valid number
  isValidNumber,
  isOptionalValidNumber,
  isNullableValidNumber,
  isNullishValidNumber,
  isValidNumberArray,
  isOptionalValidNumberArray,
  isNullableValidNumberArray,
  isNishValidNumArr,
  // String
  isString,
  isOptionalString,
  isNullableString,
  isNullishString,
  isStringArray,
  isOptionalStringArray,
  isNullableStringArray,
  isNullishStringArray,
  // "Non-Empty String"
  isNonEmptyString,
  isOptionalNonEmptyString,
  isNullableNonEmptyString,
  isNullishNonEmptyString,
  isNonEmptyStringArray,
  isOptionalNonEmptyStringArray,
  isNullableNonEmptyStringArray,
  isNullishNonEmptyStringArray,
  // Symbol
  isSymbol,
  isOptionalSymbol,
  isNullableSymbol,
  isNullishSymbol,
  isSymbolArray,
  isOptionalSymbolArray,
  isNullableSymbolArray,
  isNullishSymbolArray,
  // Date
  isDate,
  isOptionalDate,
  isNullableDate,
  isNullishDate,
  isDateArray,
  isOptionalDateArray,
  isNullableDateArray,
  isNullishDateArray,
  // Valid Date
  isValidDate,
  isOptionalValidDate,
  isNullableValidDate,
  isNullishValidDate,
  isValidDateArray,
  isOptionalValidDateArray,
  isNullableValidDateArray,
  isNullishValidDateArray,
  // Object
  isObject,
  isOptionalObject,
  isNullableObject,
  isNullishObject,
  isObjectArray,
  isOptionalObjectArray,
  isNullableObjectArray,
  isNullishObjectArray,
  // Plain Object
  isPlainObject,
  isOptionalPlainObject,
  isNullablePlainObject,
  isNullishPlainObject,
  isPlainObjectArray,
  isOptionalPlainObjectArray,
  isNullablePlainObjectArray,
  isNullishPlainObjectArray,
  toPlainObject,
  // Function
  isFunction,
  isOptionalFunction,
  isNullableFunction,
  isNullishFunction,
  isFunctionArray,
  isOptionalFunctionArray,
  isNullableFunctionArray,
  isNullishFunctionArray,
  // hasKey
  hasKey,
} = markSafeIterative(basicValidatorsRaw);

export { type PlainObject } from './basic.js';

export {
  // Is valid string
  isValidString,
  isOptionalValidString,
  isNullableValidString,
  isNullishValidString,
  // Is in array
  isInArray,
  isOptionalInArray,
  isNullableInArray,
  isNullishInArray,
  // Is valid array
  isValidArray,
  isOptionalValidArray,
  isNullableValidArray,
  isNullishValidArray,
  // Is in range
  isInRange,
  isOptionalInRange,
  isNullableInRange,
  isNullishInRange,
  isInRangeArray,
  isOptionalInRangeArray,
  isNullableInRangeArray,
  isNullishInRangeArray,
  // Is Key Of
  isKeyOf,
  isOptionalKeyOf,
  isNullableKeyOf,
  isNullishKeyOf,
  // Is Value Of
  isValueOf,
  isOptionalValueOf,
  isNullableValueOf,
  isNullishValueOf,
  type ValueOf,
} from './complex/index.js';
